### ISSUE TITLE
Delete "Protagonist" operator from OperatorsList.xml file

### ISSUE THREAD

**Issue by billmaya** [storytron/swat#20]
This is on line 3502. Since you can't select any actor as the protagonist, i.e. the first actor is always the protagonist, it could result in scripts being created that don't work.

Update 11/19/18: This operator should not be deleted at this time until someone goes through all the existing sample storyworlds and replaces the Protagonist references with the correct actor. Otherwise, when you try to load an old storyworld that uses Protagonist and the Protagonist operator has been removed from the OperatorsList.xml file, you will get the following error message—"I found an unknown operator Protagonist when reading the script."

**Comment by jawit-kien** [comment]
Thanks for helping me understand the code better. Based on your comments, the following questions come to mind:
Would it work if the Protagonist is the first actor ?  And what is the difference between the Protagonist operator and the Protagonist actor ?

Also, I'm having trouble finding the OperatorsList.xml file in the repository. Where is it?
