### ISSUE TITLE
As an author, I would like to be able to create a new storyworld using a menu selection instead of opening an existing storyworld and saving it under a new name

### ISSUE THREAD

**Issue by billmaya** [storytron/swat#5]

**Comment by ChrisPC** [comment]
Could it create a clone of Barebones.stw? Hopefully without needing to recreate it in code.

**Comment by billmaya** [comment]
I would like to create a storyworld file via code but I don't have enough Java skills and Storytron knowledge right now to do that.

What I'm going to do for this first pass is prompt the user for a new filename and location and then make a copy of the /testdata/starter.stw file to the new location with the new name (starter.stw is a copy of testdata.stw which mimics Barebones.stw).

**Comment by billmaya** [comment]
Merged wjtm/new_menu branch into master on 11/10/18. Deleted wjtm/new_menu branch.
