### ISSUE TITLE
As an author, I would like the sounds on/off dialog replaced with toggleable menu item

### ISSUE THREAD

**Issue by ChrisPC** [storytron/swat#7]

**Comment by billmaya** [comment]
Change Sounds menu item at bottom of Edit menu to Settings. Selecting Settings brings up dialog box with sound toggling option.

**Comment by billmaya** [comment]
Actually a better idea might be to change the text of the Sounds menu item to "Sounds On" and make it a JCheckBoxMenuItem instead of a JMenuItem. The checkbox menu item would be selected by default and the sounds would be on.

**Comment by billmaya** [comment]
wjtm/sound_toggle merged into master on 11/17/1. Deleted wjtm/sound_toggle.
